title: "Habit Tracker - Plan, Succeed"
description: "Documentation for Habit Tracker Mobile, a simple application to help you build and maintain good habits. Copyright © 2024, Johnny C Watt."
baseurl: "/Habit-Tracker-Mobile"
url: "https://johnnycwatt.github.io"
theme: minima
